# Generated by Django 5.1.7 on 2025-03-15 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='productkeys',
            name='product',
        ),
        migrations.AddField(
            model_name='productkeys',
            name='key',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('specifications_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productkeys')),
                ('specifications_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productvalues')),
            ],
        ),
    ]
