# Generated by Django 5.1.7 on 2025-03-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
