# Generated by Django 5.1.7 on 2025-03-23 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_customers_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
